# Generated by Django 3.2.8 on 2021-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcadeAPI', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='used_coints',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
