# Generated by Django 3.2.8 on 2021-11-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcadeAPI', '0003_action_used_coints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='used_coints',
            new_name='used_coins',
        ),
    ]
